select * from customer limit 20
-- -- 1. total revenue generated by male vs female customers
-- select gender , sum(purchase_amount) as revenue
-- from customer
-- group by gender
-- -- 2. Which customers used a discount but still spent more than the average purchase amount?
-- select customer_id , purchase_amount
-- from customer
-- where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)
-- --3. which are the top 5 products with highest average review rating ?
-- select item_purchased as products , ROUND(AVG(review_rating)::numeric, 2) AS rating
-- from customer
-- group by item_purchased
-- order by rating desc 
-- limit 5
-- -- 4. compare the average purchase amounts between standard and express shipping 
-- select shipping_type , avg(purchase_Amount) as avg_purchase_amount
-- from customer
-- where shipping_type = 'Express' or shipping_type = 'Standard'
-- group by shipping_type
-- --5. do subscribed customer spend more? compare the average spend and total revenue between the subcribers and non-subscribers
-- select distinct subscription_status ,
-- count(customer_id) as total_customers,
-- avg(purchase_amount) as average_spend ,
-- sum(purchase_amount) as total_revenue
-- from customer
-- group by subscription_status
-- order by total_revenue , average_spend

--6. Which 5 products have the highest percentage of purchases with discount applied 
-- select item_purchased as products , (avg(purchase_amount)/100) as percentage_of_purchases
-- from customer
-- where discount_applied ='Yes'
-- group by item_purchased
-- order by  percentage_of_purchases desc
-- limit 5 

-- select item_purchased ,
-- round(100 * sum(case when discount_applied ='Yes' then 1 else 0 end)/count(*), 2) as discount_rate
-- from customer
-- group by item_purchased
-- order by discount_rate desc
-- limit 5;

-- -- 7. segment customers into new , returning and loyal based on their total number of previous purchases ,
-- -- and show the count of the each segment
-- WITH customer_type AS (
--     SELECT 
--         customer_id, 
--         previous_purchases,
--         CASE 
--             WHEN previous_purchases = 1 THEN 'New'
--             WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
--             ELSE 'Loyal'
--         END AS customer_segment
--     FROM customer
-- )
-- SELECT 
--     customer_segment, 
--     COUNT(*) AS "Number of Customers"
-- FROM customer_type
-- GROUP BY customer_segment;

-- --8. what is the 3 most purchased products within each category?
-- with item_counts as (
-- select category , 
-- item_purchased,
-- count(customer_id) as total_orders,
-- row_number() over(partition by category order by count(customer_id) desc) as item_rank
-- from customer
-- group by category , item_purchased 
-- )
-- select item_rank , category , item_purchased , total_orders
-- from item_counts
-- where item_rank <= 3 ;

-- --9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- select subscription_status,
-- count(customer_id) as repeat_buyers
-- from customer
-- where previous_purchases > 5
-- group by subscription_status

--10. what is the revenue contribution of the age group ?
select age_group ,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;







